#spring.data.mongodb.uri=mongodb+srv://cdkachhadiyab50_db_user:kwZ3D9T5naf1hm4U@cluster0.sjxjcal.mongodb.net/?appName=Cluster0
#spring.data.mongodb.database=journaldb

##spring.data.mongodb.username=myjournaluser
##spring.data.mongodb.password=mypassword
#spring.data.mongodb.auto-index-creation=true
#server.servlet.context-path=\journal